# Generated by Django 3.2.6 on 2021-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
