# Generated by Django 3.2.6 on 2021-08-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
